### ISSUE TITLE
Ask for Advice for link prediction

### ISSUE THREAD

**Issue by WangXin93** [vuptran/graph-representation-learning#1]
Hi, 

Thanks for your excellent work, I am trying to leverage your method to my research problem which is fashion garment compatibility.

I want to know is there any way to make the algorithm to **predict adjacent matrix from scratch based on node features**? Because for fashion compatibility problem, it is more often to predict compatibility of a set of clothes without any existing links between them.

Looking forward to your advice.

**Comment by vuptran** [comment]
Your question refers to the *cold start* problem that is common in network analysis when the links are unknown. You will need to predict links based on node features alone. Here is an article on the cold start problem: https://hal.inria.fr/inria-00485619/document

**Comment by Abhinav43** [comment]
@WangXin93 did you find any method how to do link prediction using this method?

@vuptran  If I want to use for link prediction how can I go for that with this network?

Thank you for this awesome work :)
