### ISSUE TITLE
General question on retraining and transfer learning

### ISSUE THREAD

**Issue by idanh** [vuptran/graph-representation-learning#5]
Hi @vuptran,
Thanks for creating this library!

I've got a more general question on retraining, locality and transfer learning.
Say I have a graph G_1, and another graph G_2. And let G_1 > G_2 in terms of edges and vertices.

Is it logically correct that if indeed the two graphs represents the same underlaying idea (i.e both represent social connections like facebook) but G_2 differs in that it has not edges to G_1, to train on subset of G_1 and validate on G_2?

Does the overall idea is to learn locality on subgraphs of G_1, or does it learn a more global structure?

And finally (if I may :)), would it be feasible to use a trained network that represents the same idea of a social graph (like facebook's) but to continue from a checkpoint or lock all layers expect the last one and retrain on a similar graph?

Again thank you so much for this and have a nice day!
- Idan

**Comment by vuptran** [comment]
Your question about transfer learning across graphs is about inductive reasoning. This method is about transductive reasoning, where the full adjacency matrix must be known in advance. Maybe this reference paper may help: https://arxiv.org/abs/1706.02216

**Comment by idanh** [comment]
@vuptran Thank you for your answer. Indeed this answer part of my question(s).
The other part which I hope is possible and is the use case I'm more interested in (and I'll phrase this loosely):

Given changes over time in a graph, for example new nodes or new edges:
- Is it possible to predict missing edges or links for the new nodes
- Is it possible to update the model, without retraining it fully to the new nodes and edges added (as this may effect performance in prediction of links)

(I note that I understand from your answer above that those are not possible, but would like to re-iterate this since I am not completely sure.)

Thank you for linking the paper, and I will sure to go over this as well. And thank you for taking the time to answer my last question.

**Comment by vuptran** [comment]
Again, your question refers to inductive reasoning on graphs, which is not possible with my method because the complete (fixed) adjacency matrix must be known in advance. So the model must be retrained if new nodes are added to the network. However it may be possible to extend this research to be adaptable to dynamic networks where nodes can be dropped or added. Take a look at this paper: DepthLGP: Learning Embeddings of Out-of-Sample Nodes in Dynamic Networks

**Comment by idanh** [comment]
@vuptran again, thank you! Have a nice day.
